id: P008157
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25153
  title: ལས་འབྲས་ཀྱི་རྣམ་གཞག་བཤད་པའི་ལས་འབྲས་གསལ་བའི་མེ་ལོང་སོགས།
  author: ''
  volumes:
    0c8c4ab8c7cd4b94a01bc56367dd1609:
      image_group_id: I1KG25155
      title: ''
      volume_number: 1
      total_pages: 586
ebook_metadata:
  title: ལས་འབྲས་ཀྱི་རྣམ་གཞག་བཤད་པའི་ལས་འབྲས་གསལ་བའི་མེ་ལོང་སོགས།
  author: ''
  sku: P008157
  cover: cover.jpg
  layers:
  - pagination
