id: I800849EE
legacy_id: P008157
ocr_import_info:
  bdrc_scan_id: W1KG25153
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T11:54:24'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T14:07:57.202400+00:00'
last_modified: 2022-08-31 22:08:20.188229
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG25153
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG25153
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལས་འབྲས་ཀྱི་རྣམ་གཞག་བཤད་པའི་ལས་འབྲས་གསལ་བའི་མེ་ལོང་སོགས།
  author: བཙུན་པ་བློ་བཟང་སྙན་གྲགས།
statistics:
  ocr_word_mean_confidence_index: 0.7293415986144711
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I1KG25155:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG25155
      total_pages: 586
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG25155.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.7293415986144711
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
