id: I800849EE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:58:16+00:00'
last_modified: '2022-06-09T04:54:04.391643+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25153
  title: ལས་འབྲས་ཀྱི་རྣམ་གཞག་བཤད་པའི་ལས་འབྲས་གསལ་བའི་མེ་ལོང་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    23C4:
      image_group_id: I1KG25155
      title: Volume 1 of las 'bras kyi rnam gzhag bshad pa'i las 'bras gsal ba'i me
        long sogs/
      total_pages: 586
      order: 1
      base_file: 23C4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
